# Generated by Django 4.1.1 on 2022-09-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='orden',
            field=models.IntegerField(null=True),
        ),
    ]
